-i ${ROOT_D}/include
-i ${ROOT_D}/sub/uvm_practice/include

${ROOT_D}/sub/uvm_practice/package/cf_math_pkg.sv
${ROOT_D}/sub/uvm_practice/package/apb_pkg.sv
${ROOT_D}/sub/uvm_practice/package/axi_pkg.sv
${ROOT_D}/sub/uvm_practice/package/base_pkg.sv
${ROOT_D}/package/tb_pkg.sv

${ROOT_D}/sub/uvm_practice/design/demux.sv
${ROOT_D}/sub/uvm_practice/design/uart_tx.sv
${ROOT_D}/sub/uvm_practice/design/err_gen.sv
${ROOT_D}/sub/uvm_practice/design/uart_top.sv
${ROOT_D}/sub/uvm_practice/design/axi_fifo.sv
${ROOT_D}/sub/uvm_practice/design/axi_demux_simple.sv
${ROOT_D}/sub/uvm_practice/design/axi_demux_id_counters.sv
${ROOT_D}/sub/uvm_practice/design/spill_register_flushable.sv
${ROOT_D}/sub/uvm_practice/design/delta_counter.sv
${ROOT_D}/sub/uvm_practice/design/axi_to_axi_lite.sv
${ROOT_D}/sub/uvm_practice/design/uart_reg_if.sv
${ROOT_D}/sub/uvm_practice/design/apb_to_simple_if.sv
${ROOT_D}/sub/uvm_practice/design/onehot_to_bin.sv
${ROOT_D}/sub/uvm_practice/design/gray_to_bin.sv
${ROOT_D}/sub/uvm_practice/design/axi_burst_splitter_counters.sv
${ROOT_D}/sub/uvm_practice/design/axi_atop_filter.sv
${ROOT_D}/sub/uvm_practice/design/edge_detector.sv
${ROOT_D}/sub/uvm_practice/design/mem.sv
${ROOT_D}/sub/uvm_practice/design/axi_demux.sv
${ROOT_D}/sub/uvm_practice/design/stream_register.sv
${ROOT_D}/sub/uvm_practice/design/apb_wrapper.sv
${ROOT_D}/sub/uvm_practice/design/rr_arb_tree.sv
${ROOT_D}/sub/uvm_practice/design/register_dual_flop.sv
${ROOT_D}/sub/uvm_practice/design/register.sv
${ROOT_D}/sub/uvm_practice/design/cdc_fifo.sv
${ROOT_D}/sub/uvm_practice/design/dff.sv
${ROOT_D}/sub/uvm_practice/design/lzc.sv
${ROOT_D}/sub/uvm_practice/design/apb_fsm.sv
${ROOT_D}/sub/uvm_practice/design/axi_burst_splitter.sv
${ROOT_D}/sub/uvm_practice/design/uart_rx.sv
${ROOT_D}/sub/uvm_practice/design/fifo_v3.sv
${ROOT_D}/sub/uvm_practice/design/id_queue.sv
${ROOT_D}/sub/uvm_practice/design/axi_err_slv.sv
${ROOT_D}/sub/uvm_practice/design/spill_register.sv
${ROOT_D}/sub/uvm_practice/design/bin_to_gray.sv
${ROOT_D}/sub/uvm_practice/design/decoder.sv
${ROOT_D}/sub/uvm_practice/design/clk_div.sv
${ROOT_D}/sub/uvm_practice/design/axi_to_axi_lite_id_reflect.sv
${ROOT_D}/sub/uvm_practice/design/mux.sv
${ROOT_D}/sub/uvm_practice/design/counter.sv
${ROOT_D}/sub/uvm_practice/design/axi_burst_splitter_ax_chan.sv
${ROOT_D}/sub/uvm_practice/design/axi_to_simple_if.sv

${ROOT_D}/test/uvm/interfaces/tb_intf.sv
${ROOT_D}/test/uvm/interfaces/axi_intf.sv
${ROOT_D}/test/uvm/interfaces/uart_intf.sv
${ROOT_D}/test/uvm/seq_items/tb_seq_item.sv
${ROOT_D}/test/uvm/seq_items/uart_tx_seq_item.sv
${ROOT_D}/test/uvm/seq_items/uart_rx_seq_item.sv
${ROOT_D}/test/uvm/seq_items/reg_req_seq_item.sv
${ROOT_D}/test/uvm/seq_items/reg_rsp_seq_item.sv
${ROOT_D}/test/uvm/sequences/apply_reset_sequence.sv
${ROOT_D}/test/uvm/sequences/send_rx_sequence.sv
${ROOT_D}/test/uvm/sequences/send_axi_sequence.sv
${ROOT_D}/test/uvm/components/tb/tb_sequencer.sv
${ROOT_D}/test/uvm/components/tb/tb_driver.sv
${ROOT_D}/test/uvm/components/tb/tb_monitor.sv
${ROOT_D}/test/uvm/components/tb/tb_agent.sv
${ROOT_D}/test/uvm/components/uart/uart_monitor.sv
${ROOT_D}/test/uvm/components/uart/uart_sequencer.sv
${ROOT_D}/test/uvm/components/uart/uart_driver.sv
${ROOT_D}/test/uvm/components/uart/uart_agent.sv
${ROOT_D}/test/uvm/components/axi/axi_monitor.sv
${ROOT_D}/test/uvm/components/axi/axi_sequencer.sv
${ROOT_D}/test/uvm/components/axi/axi_driver.sv
${ROOT_D}/test/uvm/components/axi/axi_agent.sv
${ROOT_D}/test/uvm/scoreboards/simple_scoreboard.sv
${ROOT_D}/test/uvm/environments/simple_env.sv
${ROOT_D}/test/uvm/testcases/base_test.sv
${ROOT_D}/test/uvm/uvm_tb_top.sv

